"""PDF/A-3 board report generator — HTML-based compliance report for Geschäftsführer / CISO.

Generates a structured HTML document with ISO 19005-3 (PDF/A-3) metadata headers
ready for downstream conversion.  Deterministic output, no LLM calls.
"""

from __future__ import annotations

import logging
from datetime import UTC, datetime
from html import escape

logger = logging.getLogger(__name__)

# ISO 19005-3 (PDF/A-3) metadata for downstream converters
PDF_A3_METADATA: dict[str, str] = {
    "pdfa_version": "3",
    "pdfa_conformance": "B",
    "pdfa_standard": "ISO 19005-3",
    "dc_title": "Compliance Board Report",
    "dc_creator": "ComplianceHub Enterprise",
    "dc_description": "Automated compliance board report generated by ComplianceHub",
    "xmp_creator_tool": "ComplianceHub PDF/A-3 Generator v1.0",
    "pdfaid_part": "3",
    "pdfaid_conformance": "B",
}


def _render_traffic_light(score: float) -> str:
    """Return traffic-light emoji based on compliance score threshold."""
    if score >= 75.0:
        return "🟢"
    if score >= 50.0:
        return "🟡"
    return "🔴"


def _traffic_light_class(score: float) -> str:
    """Return CSS class name for traffic-light colouring."""
    if score >= 75.0:
        return "green"
    if score >= 50.0:
        return "amber"
    return "red"


def _build_heatmap_html(norm_scores: list[dict]) -> str:
    """Build an HTML table heat-map of risks by norm × severity.

    Each entry in *norm_scores* should have keys: ``norm``, ``severity``
    (``critical`` / ``high`` / ``medium`` / ``low``), and ``count``.
    """
    severity_levels = ["critical", "high", "medium", "low"]
    norms: dict[str, dict[str, int]] = {}
    for entry in norm_scores:
        norm = entry.get("norm", "Unknown")
        sev = entry.get("severity", "low")
        count = int(entry.get("count", 0))
        norms.setdefault(norm, {s: 0 for s in severity_levels})
        if sev in severity_levels:
            norms[norm][sev] += count

    rows: list[str] = []
    for norm, sevs in sorted(norms.items()):
        cells = "".join(
            f'<td class="heatmap-{s}" style="text-align:center;">{sevs[s]}</td>'
            for s in severity_levels
        )
        rows.append(f"<tr><td>{escape(norm)}</td>{cells}</tr>")

    header_cells = "".join(f"<th>{s.title()}</th>" for s in severity_levels)
    return (
        '<table class="heatmap-table" border="1" cellpadding="6" cellspacing="0">'
        f"<thead><tr><th>Norm</th>{header_cells}</tr></thead>"
        f'<tbody>{"".join(rows)}</tbody></table>'
    )


def _build_findings_html(findings: list[dict]) -> str:
    """Render top-5 critical findings with open measures."""
    top5 = findings[:5]
    if not top5:
        return "<p>No critical findings reported.</p>"
    items: list[str] = []
    for idx, f in enumerate(top5, 1):
        title = escape(str(f.get("title", "Untitled")))
        norm = escape(str(f.get("norm", "")))
        measures = f.get("open_measures", [])
        measure_items = "".join(
            f"<li>{escape(str(m))}</li>" for m in measures
        )
        measure_list = f"<ul>{measure_items}</ul>" if measure_items else "<em>None</em>"
        items.append(
            f"<div class='finding'><h4>{idx}. {title} ({norm})</h4>"
            f"<p><strong>Open Measures:</strong></p>{measure_list}</div>"
        )
    return "".join(items)


def _build_incident_stats_html(incidents: dict) -> str:
    """Render incident statistics table for NIS2/DSGVO."""
    nis2 = incidents.get("nis2", {})
    dsgvo = incidents.get("dsgvo", {})
    return (
        '<table border="1" cellpadding="6" cellspacing="0">'
        "<thead><tr><th>Category</th><th>Total</th><th>Open</th><th>Resolved</th></tr></thead>"
        "<tbody>"
        f"<tr><td>NIS2</td><td>{nis2.get('total', 0)}</td>"
        f"<td>{nis2.get('open', 0)}</td><td>{nis2.get('resolved', 0)}</td></tr>"
        f"<tr><td>DSGVO</td><td>{dsgvo.get('total', 0)}</td>"
        f"<td>{dsgvo.get('open', 0)}</td><td>{dsgvo.get('resolved', 0)}</td></tr>"
        "</tbody></table>"
    )


def _build_deadlines_html(deadlines: list[dict]) -> str:
    """Render upcoming regulatory deadlines."""
    if not deadlines:
        return "<p>No upcoming deadlines.</p>"
    rows = "".join(
        f"<tr><td>{escape(str(d.get('regulation', '')))}</td>"
        f"<td>{escape(str(d.get('deadline', '')))}</td>"
        f"<td>{escape(str(d.get('description', '')))}</td></tr>"
        for d in deadlines
    )
    return (
        '<table border="1" cellpadding="6" cellspacing="0">'
        "<thead><tr><th>Regulation</th><th>Deadline</th><th>Description</th></tr></thead>"
        f"<tbody>{rows}</tbody></table>"
    )


def generate_board_pdf_report(kpi_data: dict, tenant_id: str) -> bytes:
    """Generate an HTML board report structured for PDF/A-3 conversion.

    Returns UTF-8 encoded HTML bytes with embedded PDF/A-3 metadata.
    The report includes: cover page, executive summary with traffic-light
    scoring, heat-map, top-5 findings, incident statistics, upcoming
    deadlines, and a signature block.
    """
    now = datetime.now(UTC)
    tenant_name = escape(str(kpi_data.get("tenant_name", tenant_id)))
    reporting_period = escape(str(kpi_data.get("reporting_period", now.strftime("%Y-%m"))))
    overall_score = float(kpi_data.get("overall_score", 0.0))
    traffic = _render_traffic_light(overall_score)
    traffic_css = _traffic_light_class(overall_score)

    norm_scores = kpi_data.get("norm_scores", [])
    findings = kpi_data.get("critical_findings", [])
    incidents = kpi_data.get("incidents", {})
    deadlines = kpi_data.get("deadlines", [])

    heatmap_html = _build_heatmap_html(norm_scores)
    findings_html = _build_findings_html(findings)
    incidents_html = _build_incident_stats_html(incidents)
    deadlines_html = _build_deadlines_html(deadlines)

    # Build PDF/A-3 metadata as HTML meta tags
    meta_tags = "\n    ".join(
        f'<meta name="pdfa:{k}" content="{escape(v)}" />'
        for k, v in PDF_A3_METADATA.items()
    )

    html = f"""<!DOCTYPE html>
<html lang="de">
<head>
    <meta charset="UTF-8" />
    <meta name="generator" content="ComplianceHub PDF/A-3 Generator" />
    <meta name="dcterms.created" content="{now.isoformat()}" />
    <meta name="pdfa:part" content="3" />
    <meta name="pdfa:conformance" content="B" />
    {meta_tags}
    <title>Compliance Board Report — {tenant_name}</title>
    <style>
        body {{ font-family: 'Helvetica Neue', Arial, sans-serif; margin: 40px; color: #222; }}
        h1, h2, h3 {{ color: #1a3a5c; }}
        .cover {{ text-align: center; margin-bottom: 60px; page-break-after: always; }}
        .cover h1 {{ font-size: 2em; }}
        .score-badge {{ font-size: 1.5em; padding: 10px 20px; border-radius: 8px; display: inline-block; }}
        .score-badge.green {{ background: #d4edda; color: #155724; }}
        .score-badge.amber {{ background: #fff3cd; color: #856404; }}
        .score-badge.red {{ background: #f8d7da; color: #721c24; }}
        table {{ border-collapse: collapse; width: 100%; margin: 12px 0; }}
        th {{ background: #1a3a5c; color: #fff; padding: 8px; }}
        td {{ padding: 6px 8px; }}
        .heatmap-critical {{ background: #f8d7da; }}
        .heatmap-high {{ background: #fff3cd; }}
        .heatmap-medium {{ background: #d4edda; }}
        .heatmap-low {{ background: #cce5ff; }}
        .signature-block {{ margin-top: 60px; display: flex; gap: 80px; }}
        .signature-line {{ border-top: 1px solid #222; width: 250px; padding-top: 4px; text-align: center; }}
        .finding {{ margin-bottom: 16px; }}
        @media print {{ .cover {{ page-break-after: always; }} }}
    </style>
</head>
<body>

<!-- Cover Page -->
<div class="cover">
    <h1>Compliance Board Report</h1>
    <h2>{tenant_name}</h2>
    <p><strong>Reporting Period:</strong> {reporting_period}</p>
    <p><strong>Created:</strong> {now.strftime("%d.%m.%Y %H:%M")} UTC</p>
    <p><em>Generated by ComplianceHub Enterprise</em></p>
</div>

<!-- Executive Summary -->
<h2>1. Executive Summary</h2>
<p>
    Overall Compliance Score:
    <span class="score-badge {traffic_css}">
        {traffic} {overall_score:.1f}%
    </span>
</p>

<!-- Risk Heat Map -->
<h2>2. Risk Heat Map (Norm × Severity)</h2>
{heatmap_html}

<!-- Top-5 Critical Findings -->
<h2>3. Top-5 Critical Findings</h2>
{findings_html}

<!-- Incident Statistics -->
<h2>4. Incident Statistics (NIS2 / DSGVO)</h2>
{incidents_html}

<!-- Upcoming Deadlines -->
<h2>5. Upcoming Deadlines</h2>
{deadlines_html}

<!-- Signature Block -->
<h2>6. Approval</h2>
<div class="signature-block">
    <div>
        <div class="signature-line">CISO</div>
        <p>Date: _______________</p>
    </div>
    <div>
        <div class="signature-line">Geschäftsführer</div>
        <p>Date: _______________</p>
    </div>
</div>

</body>
</html>"""

    logger.info(
        "board_pdf_report_generated tenant=%s period=%s score=%.1f",
        tenant_id,
        reporting_period,
        overall_score,
    )
    return html.encode("utf-8")
