/**
 * Wave 47 – Vordefinierte SLA-Regeln (wenige, erklärbare Schwellen).
 */

import type { AdvisorSlaRuleDefinition } from "@/lib/advisorSlaTypes";

export const ADVISOR_SLA_DEFAULT_RULES: AdvisorSlaRuleDefinition[] = [
  {
    rule_id: "sla_review_coverage_warn",
    tenant_id: null,
    scope: "review",
    condition_type: "threshold_kpi",
    metric_key: "kpi.review.current_share",
    operator: "lt",
    threshold: 0.75,
    severity: "warning",
    active: true,
    label_de: "Review-Deckung unter Zielkorridor",
  },
  {
    rule_id: "sla_review_coverage_critical",
    tenant_id: null,
    scope: "review",
    condition_type: "threshold_kpi",
    metric_key: "kpi.review.current_share",
    operator: "lt",
    threshold: 0.55,
    severity: "critical",
    active: true,
    label_de: "Review-Deckung kritisch niedrig",
  },
  {
    rule_id: "sla_review_mean_age_warn",
    tenant_id: null,
    scope: "review",
    condition_type: "threshold_age",
    metric_key: "kpi.review.mean_age_days",
    operator: "gt",
    threshold: 180,
    severity: "warning",
    active: true,
    label_de: "Durchschnittliches Review-Alter hoch",
  },
  {
    rule_id: "sla_export_fresh_warn",
    tenant_id: null,
    scope: "export",
    condition_type: "threshold_kpi",
    metric_key: "kpi.export.fresh_share",
    operator: "lt",
    threshold: 0.65,
    severity: "warning",
    active: true,
    label_de: "Export-Kadenz unter Ziel",
  },
  {
    rule_id: "sla_export_fresh_critical",
    tenant_id: null,
    scope: "export",
    condition_type: "threshold_kpi",
    metric_key: "kpi.export.fresh_share",
    operator: "lt",
    threshold: 0.45,
    severity: "critical",
    active: true,
    label_de: "Export-Kadenz kritisch",
  },
  {
    rule_id: "sla_reminder_backlog_warn",
    tenant_id: null,
    scope: "reminder",
    condition_type: "threshold_count",
    metric_key: "payload.open_reminders_total",
    operator: "gt",
    threshold: 12,
    severity: "warning",
    active: true,
    label_de: "Reminder-Backlog erhöht",
  },
  {
    rule_id: "sla_reminder_backlog_critical",
    tenant_id: null,
    scope: "reminder",
    condition_type: "threshold_count",
    metric_key: "payload.open_reminders_total",
    operator: "gt",
    threshold: 25,
    severity: "critical",
    active: true,
    label_de: "Reminder-Backlog hoch",
  },
  {
    rule_id: "sla_reminder_overdue_warn",
    tenant_id: null,
    scope: "reminder",
    condition_type: "threshold_count",
    metric_key: "payload.reminders_overdue_today",
    operator: "gte",
    threshold: 3,
    severity: "warning",
    active: true,
    label_de: "Überfällige / heute fällige Reminder",
  },
  {
    rule_id: "sla_reminder_overdue_critical",
    tenant_id: null,
    scope: "reminder",
    condition_type: "threshold_count",
    metric_key: "payload.reminders_overdue_today",
    operator: "gte",
    threshold: 8,
    severity: "critical",
    active: true,
    label_de: "Viele überfällige Reminder",
  },
  {
    rule_id: "sla_gaps_queue_warn",
    tenant_id: null,
    scope: "gaps",
    condition_type: "threshold_count",
    metric_key: "payload.attention_queue_size",
    operator: "gte",
    threshold: 6,
    severity: "warning",
    active: true,
    label_de: "Attention-Queue groß",
  },
  {
    rule_id: "sla_gaps_queue_critical",
    tenant_id: null,
    scope: "gaps",
    condition_type: "threshold_count",
    metric_key: "payload.attention_queue_size",
    operator: "gte",
    threshold: 10,
    severity: "critical",
    active: true,
    label_de: "Attention-Queue stark belastet",
  },
  {
    rule_id: "sla_gaps_red_pillar_warn",
    tenant_id: null,
    scope: "gaps",
    condition_type: "threshold_kpi",
    metric_key: "kpi.hygiene.share_no_red_pillar",
    operator: "lt",
    threshold: 0.55,
    severity: "warning",
    active: true,
    label_de: "Viele Mandanten mit roter Säule",
  },
  {
    rule_id: "sla_gaps_review_stale_spread",
    tenant_id: null,
    scope: "gaps",
    condition_type: "threshold_count",
    metric_key: "payload.review_stale_mandanten",
    operator: "gte",
    threshold: 4,
    severity: "critical",
    active: true,
    label_de: "Breite Review-Rückstände",
  },
  {
    rule_id: "sla_export_never_critical",
    tenant_id: null,
    scope: "export",
    condition_type: "threshold_count",
    metric_key: "payload.never_export_mandanten",
    operator: "gte",
    threshold: 2,
    severity: "critical",
    active: true,
    label_de: "Mandanten ohne jemals Export",
  },
];
